In [1]:
import pandas as pd
import numpy as np
#import matplotlib.pyplot as plt
#import seaborn as sns

In [2]:
url = "https://data.cityofnewyork.us/api/v3/views/w2pb-icbu/query.csv"

df = pd.read_csv(url)

print(df.shape)
print(df.columns)
df.head()

(845607, 33)
Index([':id', ':version', ':created_at', ':updated_at', 'borough',
       'neighborhood', 'building_class_category', 'tax_class_as_of_final_roll',
       'block', 'lot', 'ease_ment', 'building_class_as_of_final', 'address',
       'apartment_number', 'zip_code', 'residential_units', 'commercial_units',
       'total_units', 'land_square_feet', 'gross_square_feet', 'year_built',
       'tax_class_at_time_of_sale', 'building_class_at_time_of', 'sale_price',
       'sale_date', 'latitude', 'longitude', 'community_board',
       'council_district', 'bin', 'bbl', 'census_tract_2020', 'nta'],
      dtype='object')

,:id,:version,:created_at,:updated_at,borough,neighborhood,building_class_category,tax_class_as_of_final_roll,block,lot,...,sale_price,sale_date,latitude,longitude,community_board,council_district,bin,bbl,census_tract_2020,nta
0,row-tnn2.rwjh~9cwp,rv-j6tj-vt3d_pnsr,2026-05-27T16:28:09.949Z,2026-05-27T16:28:09.949Z,1,CHINATOWN,47 CONDO NON-BUSINESS STORAGE,4,172,1490,...,1590000,2019-06-21T00:00:00.000,40.716951,-74.002500,101.0,1.0,1088222.0,1.001728e+09,31.0,MN0102
1,row-y9px~bpak.qzhk,rv-63f4.3efe~xrph,2026-05-27T16:28:09.949Z,2026-05-27T16:28:09.949Z,1,EAST VILLAGE,10 COOPS - ELEVATOR APARTMENTS,2,461,24,...,515000,2019-06-11T00:00:00.000,40.727669,-73.989201,103.0,2.0,1006622.0,1.004610e+09,38.0,MN0303
2,row-94g7~58t5.r4uw,rv-552u~2xmc~g27d,2026-05-27T16:28:09.949Z,2026-05-27T16:28:09.949Z,1,FASHION,21 OFFICE BUILDINGS,4,779,23,...,0,2019-05-03T00:00:00.000,40.748263,-73.993857,105.0,3.0,1014284.0,1.007790e+09,95.0,MN0501
3,row-cvmm_7t8f-5arx,rv-mnsb.yhkp.iqcn,2026-05-27T16:28:09.949Z,2026-05-27T16:28:09.949Z,1,FASHION,13 CONDOS - ELEVATOR APARTMENTS,2,841,1044,...,5203258,2019-03-11T00:00:00.000,40.752505,-73.982574,105.0,4.0,1090404.0,1.008418e+09,84.0,MN0502
4,row-benm_shvq~m695,rv-i8n9-psi7~s2j8,2026-05-27T16:28:09.949Z,2026-05-27T16:28:09.949Z,1,EAST VILLAGE,10 COOPS - ELEVATOR APARTMENTS,2,431,31,...,975000,2019-12-27T00:00:00.000,40.723793,-73.985602,103.0,2.0,1005762.0,1.004310e+09,32.0,MN0303

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 845607 entries, 0 to 845606
Data columns (total 33 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   :id                         845607 non-null  object
 1   :version                    845607 non-null  object
 2   :created_at                 845607 non-null  object
 3   :updated_at                 845607 non-null  object
 4   borough                     845607 non-null  int64
 5   neighborhood                845607 non-null  object
 6   building_class_category     845607 non-null  object
 7   tax_class_as_of_final_roll  841424 non-null  object
 8   block                       845607 non-null  int64
 9   lot                         845607 non-null  int64
 10  ease_ment                   0 non-null       float64
 11  building_class_as_of_final  841424 non-null  object
 12  address                     845607 non-null  object
 13  apartment_number            208671 non-null  object
 14  zip_code                    845540 non-null  float64
 15  residential_units           711941 non-null  float64
 16  commercial_units            633860 non-null  float64
 17  total_units                 726245 non-null  float64
 18  land_square_feet            619554 non-null  object
 19  gross_square_feet           619559 non-null  object
 20  year_built                  806197 non-null  float64
 21  tax_class_at_time_of_sale   845607 non-null  int64
 22  building_class_at_time_of   845607 non-null  object
 23  sale_price                  845607 non-null  int64
 24  sale_date                   845607 non-null  object
 25  latitude                    822329 non-null  float64
 26  longitude                   822329 non-null  float64
 27  community_board             822330 non-null  float64
 28  council_district            822330 non-null  float64
 29  bin                         819128 non-null  float64
 30  bbl                         819128 non-null  float64
 31  census_tract_2020           822583 non-null  float64
 32  nta                         822583 non-null  object
dtypes: float64(13), int64(5), object(15)
memory usage: 212.9+ MB

In [4]:
missing = df.isnull().sum()
missing[missing > 0].sort_values(ascending=False)

ease_ment                     845607
apartment_number              636936
land_square_feet              226053
gross_square_feet             226048
commercial_units              211747
residential_units             133666
total_units                   119362
year_built                     39410
bbl                            26479
bin                            26479
longitude                      23278
latitude                       23278
council_district               23277
community_board                23277
nta                            23024
census_tract_2020              23024
building_class_as_of_final      4183
tax_class_as_of_final_roll      4183
zip_code                          67
dtype: int64

In [5]:
missing_pct = (df.isnull().sum() / len(df) * 100).round(2)
missing_pct[missing_pct > 0].sort_values(ascending=False)

ease_ment                     100.00
apartment_number               75.32
gross_square_feet              26.73
land_square_feet               26.73
commercial_units               25.04
residential_units              15.81
total_units                    14.12
year_built                      4.66
bbl                             3.13
bin                             3.13
council_district                2.75
community_board                 2.75
longitude                       2.75
latitude                        2.75
nta                             2.72
census_tract_2020               2.72
building_class_as_of_final      0.49
tax_class_as_of_final_roll      0.49
zip_code                        0.01
dtype: float64

In [6]:
df['sale_price'].describe()

count    8.456070e+05
mean     1.366774e+06
std      1.133209e+07
min      0.000000e+00
25%      0.000000e+00
50%      4.700000e+05
75%      9.390000e+05
max      2.397502e+09
Name: sale_price, dtype: float64

In [7]:
df['sale_price'].value_counts().head(20)

0          262138
10           8901
650000       4258
750000       4110
600000       4013
700000       3933
800000       3797
850000       3704
550000       3695
1100000      3539
900000       3496
1200000      3491
950000       3406
450000       3378
400000       3267
500000       3217
1300000      2929
300000       2836
350000       2734
1250000      2572
Name: sale_price, dtype: int64

In [8]:
(df['sale_price'] <= 0).sum()

262138

In [9]:
zero_sales = df[df['sale_price'] == 0]
zero_sales['building_class_category'].value_counts().head(20)

02 TWO FAMILY DWELLINGS              60585
01 ONE FAMILY DWELLINGS              58138
13 CONDOS - ELEVATOR APARTMENTS      25943
03 THREE FAMILY DWELLINGS            20202
10 COOPS - ELEVATOR APARTMENTS       17220
07 RENTALS - WALKUP APARTMENTS       12102
02  TWO FAMILY DWELLINGS              6092
01  ONE FAMILY DWELLINGS              5573
05 TAX CLASS 1 VACANT LAND            4429
44 CONDO PARKING                      4393
04 TAX CLASS 1 CONDOS                 4115
13  CONDOS - ELEVATOR APARTMENTS      3096
22 STORE BUILDINGS                    3078
09 COOPS - WALKUP APARTMENTS          2498
14 RENTALS - 4-10 UNIT                2409
15 CONDOS - 2-10 UNIT RESIDENTIAL     2365
29 COMMERCIAL GARAGES                 2018
03  THREE FAMILY DWELLINGS            2006
12 CONDOS - WALKUP APARTMENTS         1829
07  RENTALS - WALKUP APARTMENTS       1701
Name: building_class_category, dtype: int64

In [10]:
ten_sales = df[df['sale_price'] == 10]
ten_sales['building_class_category'].value_counts().head(20)

01 ONE FAMILY DWELLINGS              2592
02 TWO FAMILY DWELLINGS              2427
13 CONDOS - ELEVATOR APARTMENTS       923
03 THREE FAMILY DWELLINGS             739
07 RENTALS - WALKUP APARTMENTS        357
01  ONE FAMILY DWELLINGS              221
02  TWO FAMILY DWELLINGS              219
10 COOPS - ELEVATOR APARTMENTS        175
04 TAX CLASS 1 CONDOS                 154
05 TAX CLASS 1 VACANT LAND             89
44 CONDO PARKING                       89
15 CONDOS - 2-10 UNIT RESIDENTIAL      77
03  THREE FAMILY DWELLINGS             74
14 RENTALS - 4-10 UNIT                 68
13  CONDOS - ELEVATOR APARTMENTS       68
12 CONDOS - WALKUP APARTMENTS          65
22 STORE BUILDINGS                     59
07  RENTALS - WALKUP APARTMENTS        44
29 COMMERCIAL GARAGES                  42
09 COOPS - WALKUP APARTMENTS           40
Name: building_class_category, dtype: int64

In [11]:
print(zero_sales['sale_date'].min(), zero_sales['sale_date'].max())
print(ten_sales['sale_date'].min(), ten_sales['sale_date'].max())

2016-01-01T00:00:00.000 2025-12-31T00:00:00.000
2016-01-01T00:00:00.000 2025-12-30T00:00:00.000

In [12]:
clean_df = df[df['sale_price'] > 10].copy()
print(clean_df.shape)
print(clean_df['sale_price'].describe())
print((clean_df['sale_price'] <= 10).sum())

(572287, 33)
count    5.722870e+05
mean     2.019535e+06
std      1.372693e+07
min      1.200000e+01
25%      4.550000e+05
50%      7.440000e+05
75%      1.277904e+06
max      2.397502e+09
Name: sale_price, dtype: float64
0

In [13]:
q1 = np.percentile(clean_df['sale_price'], 25)
q3 = np.percentile(clean_df['sale_price'], 75)

iqr = q3 - q1

print("Q1:", q1)
print("Q3:", q3)
print("IQR:", iqr)

upper_limit = q3 + 1.5 * iqr

print("Upper limit:", upper_limit)

Q1: 455000.0
Q3: 1277903.5
IQR: 822903.5
Upper limit: 2512258.75

In [14]:
outliers = clean_df[clean_df['sale_price'] > upper_limit]
print(outliers.shape)

(60792, 33)

In [15]:
outliers['borough'].value_counts()

1    36798
3    14867
4     5082
2     3416
5      629
Name: borough, dtype: int64

In [16]:
df.groupby('borough')['neighborhood'].unique()

borough
1    [CHINATOWN, EAST VILLAGE, FASHION, CHELSEA, CL...
2    [HUNTS POINT, BATHGATE, BELMONT, BRONXDALE, SO...
3    [BAY RIDGE, WILLIAMSBURG-EAST, BENSONHURST, BR...
4    [QUEENS-UNKNOWN, ASTORIA, CORONA, ELMHURST, BR...
5    [MIDLAND BEACH, TOTTENVILLE, WESTERLEIGH, ROSE...
Name: neighborhood, dtype: object

In [17]:
borough_map = {
    1: 'Manhattan',
    2: 'Bronx',
    3: 'Brooklyn',
    4: 'Queens',
    5: 'Staten Island'
}

clean_df['borough_name'] = clean_df['borough'].map(borough_map)

In [18]:
clean_df[['borough', 'borough_name']].drop_duplicates().sort_values('borough')

      borough   borough_name
0           1      Manhattan
1147        2          Bronx
2015        3       Brooklyn
4378        4         Queens
30          5  Staten Island

In [19]:
outliers['building_class_category'].value_counts().head(15)

13 CONDOS - ELEVATOR APARTMENTS      18473
10 COOPS - ELEVATOR APARTMENTS        7664
07 RENTALS - WALKUP APARTMENTS        4973
02 TWO FAMILY DWELLINGS               2643
01 ONE FAMILY DWELLINGS               2368
22 STORE BUILDINGS                    2141
13  CONDOS - ELEVATOR APARTMENTS      2055
08 RENTALS - ELEVATOR APARTMENTS      1704
15 CONDOS - 2-10 UNIT RESIDENTIAL     1389
29 COMMERCIAL GARAGES                 1262
03 THREE FAMILY DWELLINGS             1151
21 OFFICE BUILDINGS                   1113
14 RENTALS - 4-10 UNIT                 985
30 WAREHOUSES                          960
43 CONDO OFFICE BUILDINGS              796
Name: building_class_category, dtype: int64

In [20]:
clean_df['building_class_category'].str.strip().value_counts().head(15)

01 ONE FAMILY DWELLINGS              106649
10 COOPS - ELEVATOR APARTMENTS       101252
13 CONDOS - ELEVATOR APARTMENTS       89725
02 TWO FAMILY DWELLINGS               77863
09 COOPS - WALKUP APARTMENTS          21114
03 THREE FAMILY DWELLINGS             18747
07 RENTALS - WALKUP APARTMENTS        13662
01  ONE FAMILY DWELLINGS              12777
10  COOPS - ELEVATOR APARTMENTS       11987
15 CONDOS - 2-10 UNIT RESIDENTIAL     10810
04 TAX CLASS 1 CONDOS                 10400
02  TWO FAMILY DWELLINGS              10149
13  CONDOS - ELEVATOR APARTMENTS       9498
17 CONDO COOPS                         9337
44 CONDO PARKING                       7899
Name: building_class_category, dtype: int64

In [21]:
clean_df['building_class_category'].str.strip().str.replace(r'\s+', ' ', regex=True).value_counts()

01 ONE FAMILY DWELLINGS                       119426
10 COOPS - ELEVATOR APARTMENTS                113239
13 CONDOS - ELEVATOR APARTMENTS                99223
02 TWO FAMILY DWELLINGS                        88012
09 COOPS - WALKUP APARTMENTS                   23674
03 THREE FAMILY DWELLINGS                      21232
07 RENTALS - WALKUP APARTMENTS                 15717
15 CONDOS - 2-10 UNIT RESIDENTIAL              11823
04 TAX CLASS 1 CONDOS                          11601
17 CONDO COOPS                                 10470
44 CONDO PARKING                                8138
12 CONDOS - WALKUP APARTMENTS                   7392
05 TAX CLASS 1 VACANT LAND                      5846
22 STORE BUILDINGS                              5284
14 RENTALS - 4-10 UNIT                          3270
29 COMMERCIAL GARAGES                           3050
08 RENTALS - ELEVATOR APARTMENTS                2766
47 CONDO NON-BUSINESS STORAGE                   2428
43 CONDO OFFICE BUILDINGS                       2323
21 OFFICE BUILDINGS                             2261
45 CONDO HOTELS                                 1977
31 COMMERCIAL VACANT LAND                       1884
30 WAREHOUSES                                   1765
11 SPECIAL CONDO BILLING LOTS                   1214
46 CONDO STORE BUILDINGS                        1108
27 FACTORIES                                    1105
26 OTHER HOTELS                                  924
06 TAX CLASS 1 - OTHER                           813
28 COMMERCIAL CONDOS                             728
41 TAX CLASS 4 - OTHER                           717
16 CONDOS - 2-10 UNIT WITH COMMERCIAL UNIT       641
37 RELIGIOUS FACILITIES                          632
33 EDUCATIONAL FACILITIES                        281
32 HOSPITAL AND HEALTH FACILITIES                231
48 CONDO TERRACES/GARDENS/CABANAS                187
35 INDOOR PUBLIC AND CULTURAL FACILITIES         161
49 CONDO WAREHOUSES/FACTORY/INDUS                139
38 ASYLUMS AND HOMES                             115
42 CONDO CULTURAL/MEDICAL/EDUCATIONAL/ETC        110
25 LUXURY HOTELS                                 103
36 OUTDOOR RECREATIONAL FACILITIES                98
23 LOFT BUILDINGS                                 72
34 THEATRES                                       50
11A CONDO-RENTALS                                 35
39 TRANSPORTATION FACILITIES                      16
40 SELECTED GOVERNMENTAL FACILITIES                4
18 TAX CLASS 3 - UNTILITY PROPERTIES               2
Name: building_class_category, dtype: int64

In [22]:
clean_df['building_class_category'] = (
    clean_df['building_class_category']
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)
clean_df['building_class_category'].value_counts().head(15)

01 ONE FAMILY DWELLINGS              119426
10 COOPS - ELEVATOR APARTMENTS       113239
13 CONDOS - ELEVATOR APARTMENTS       99223
02 TWO FAMILY DWELLINGS               88012
09 COOPS - WALKUP APARTMENTS          23674
03 THREE FAMILY DWELLINGS             21232
07 RENTALS - WALKUP APARTMENTS        15717
15 CONDOS - 2-10 UNIT RESIDENTIAL     11823
04 TAX CLASS 1 CONDOS                 11601
17 CONDO COOPS                        10470
44 CONDO PARKING                       8138
12 CONDOS - WALKUP APARTMENTS          7392
05 TAX CLASS 1 VACANT LAND             5846
22 STORE BUILDINGS                     5284
14 RENTALS - 4-10 UNIT                 3270
Name: building_class_category, dtype: int64

In [23]:
outliers = clean_df[clean_df['sale_price'] > upper_limit].copy()
outliers.shape

(60792, 34)

In [24]:
outliers.sort_values(
    'sale_price',
    ascending=False
)[[
    'sale_price',
    'borough_name',
    'neighborhood',
    'building_class_category',
    'address'
]].head(20)

,sale_price,borough_name,neighborhood,building_class_category,address
446427,2397501899,Manhattan,CHELSEA,21 OFFICE BUILDINGS,75 9 AVENUE
369829,2210000000,Manhattan,MIDTOWN CBD,21 OFFICE BUILDINGS,245 PARK AVENUE
3911,2155000000,Manhattan,JAVITS CENTER,43 CONDO OFFICE BUILDINGS,"30 HUDSON YARDS, TW"
256656,1932900000,Manhattan,MIDTOWN WEST,21 OFFICE BUILDINGS,787 7 AVENUE
289808,1767913114,Manhattan,TRIBECA,21 OFFICE BUILDINGS,390 GREENWICH STREET
286544,1400000000,Manhattan,MIDTOWN CBD,21 OFFICE BUILDINGS,550 MADISON AVENUE
285175,1279624000,Manhattan,MIDTOWN WEST,21 OFFICE BUILDINGS,1285 AVENUE OF THE AMER
798495,1080000000,Manhattan,MIDTOWN CBD,22 STORE BUILDINGS,9 EAST 56 STREET
798496,1080000000,Manhattan,MIDTOWN CBD,22 STORE BUILDINGS,8 EAST 57 STREET
798490,1080000000,Manhattan,MIDTOWN CBD,21 OFFICE BUILDINGS,590 MADISON AVENUE
345304,1040000000,Manhattan,FINANCIAL,21 OFFICE BUILDINGS,60 WALL STREET
159091,1033000000,Manhattan,JAVITS CENTER,43 CONDO OFFICE BUILDINGS,441 NINTH AVENUE
159445,1033000000,Manhattan,JAVITS CENTER,43 CONDO OFFICE BUILDINGS,441 NINTH AVENUE
467182,980000000,Manhattan,UPPER WEST SIDE (59-79),34 THEATRES,149 COLUMBUS AVENUE
82949,978090439,Manhattan,FASHION,22 STORE BUILDINGS,424/434 5 AVENUE
641694,963000000,Manhattan,MIDTOWN CBD,43 CONDO OFFICE BUILDINGS,"717 5 AVENUE, 4-OFF"
642539,963000000,Manhattan,MIDTOWN CBD,46 CONDO STORE BUILDINGS,"717 5 AVENUE, RETL"
604215,931000000,Manhattan,UPPER WEST SIDE (59-79),34 THEATRES,149 COLUMBUS AVENUE
604429,931000000,Manhattan,UPPER WEST SIDE (59-79),34 THEATRES,77 WEST 66TH STREET
604616,931000000,Manhattan,UPPER WEST SIDE (59-79),34 THEATRES,30 WEST 67TH STREET

In [25]:
clean_df['sale_date'] = pd.to_datetime(clean_df['sale_date'])
clean_df['sale_date'].dtype

dtype('<M8[ns]')

In [26]:
clean_df[['land_square_feet', 'gross_square_feet']].head(10)

   land_square_feet gross_square_feet
0                 0                 0
1               NaN               NaN
3                 0                 0
4               NaN               NaN
5             2,380             4,666
6               NaN               NaN
7             8,305           108,000
8             2,317            10,425
12                0                 0
13                0                 0

In [27]:
clean_df[['land_square_feet', 'gross_square_feet']].dtypes

land_square_feet     object
gross_square_feet    object
dtype: object

In [28]:
clean_df['land_square_feet'] = pd.to_numeric(
    clean_df['land_square_feet'].str.replace(',', ''),
    errors='coerce'
)

In [29]:
clean_df['gross_square_feet'] = pd.to_numeric(
    clean_df['gross_square_feet'].str.replace(',', ''),
    errors='coerce'
)

In [30]:
clean_df[['land_square_feet', 'gross_square_feet']].dtypes

land_square_feet     float64
gross_square_feet    float64
dtype: object

In [31]:
clean_df[['land_square_feet', 'gross_square_feet']].head(10)

    land_square_feet  gross_square_feet
0                0.0                0.0
1                NaN                NaN
3                0.0                0.0
4                NaN                NaN
5             2380.0             4666.0
6                NaN                NaN
7             8305.0           108000.0
8             2317.0            10425.0
12               0.0                0.0
13               0.0                0.0

In [32]:
clean_df[['land_square_feet', 'gross_square_feet']].describe()

       land_square_feet  gross_square_feet
count      3.884820e+05       3.884840e+05
mean       5.357270e+03       4.566407e+03
std        1.068817e+05       4.093268e+04
min        0.000000e+00       0.000000e+00
25%        0.000000e+00       0.000000e+00
50%        2.067000e+03       1.438000e+03
75%        3.300000e+03       2.292000e+03
max        1.985040e+07       8.942176e+06

In [33]:
print("Land square feet = 0:", (clean_df['land_square_feet'] == 0).sum())
print("Land square feet missing:", clean_df['land_square_feet'].isna().sum())

print("Gross square feet = 0:", (clean_df['gross_square_feet'] == 0).sum())
print("Gross square feet missing:", clean_df['gross_square_feet'].isna().sum())

Land square feet = 0: 107316
Land square feet missing: 183805
Gross square feet = 0: 111073
Gross square feet missing: 183803

In [34]:
clean_df['year_built'].describe()

count    546009.000000
mean       1902.480265
std         312.614332
min           0.000000
25%        1925.000000
50%        1950.000000
75%        1975.000000
max        2025.000000
Name: year_built, dtype: float64

In [35]:
(clean_df['year_built'] == 0).sum()

14176

In [36]:
clean_df['year_built'] = clean_df['year_built'].replace(0, np.nan)

In [37]:
clean_df['year_built'].describe()

count    531833.000000
mean       1953.190846
std          35.847290
min         190.000000
25%        1925.000000
50%        1950.000000
75%        1975.000000
max        2025.000000
Name: year_built, dtype: float64

In [38]:
(clean_df['year_built'] < 1800).sum()

5

In [39]:
clean_df[clean_df['year_built'] < 1800][
    ['borough_name', 'neighborhood', 'building_class_category', 'year_built', 'sale_price']
]

,borough_name,neighborhood,building_class_category,year_built,sale_price
66535,Queens,RIDGEWOOD,15 CONDOS - 2-10 UNIT RESIDENTIAL,1030.0,485000
82344,Manhattan,CHELSEA,29 COMMERCIAL GARAGES,1111.0,7680000
365624,Manhattan,CHELSEA,29 COMMERCIAL GARAGES,1111.0,8208750
522290,Brooklyn,BAY RIDGE,13 CONDOS - ELEVATOR APARTMENTS,220.0,890228
795725,Manhattan,GREENWICH VILLAGE-WEST,13 CONDOS - ELEVATOR APARTMENTS,190.0,10250000

In [40]:
clean_df.loc[clean_df['year_built'] < 1800, 'year_built'] = np.nan

In [41]:
print((clean_df['year_built'] < 1800).sum())
clean_df['year_built'].describe()

0

count    531828.000000
mean       1953.202323
std          35.626904
min        1800.000000
25%        1925.000000
50%        1950.000000
75%        1975.000000
max        2025.000000
Name: year_built, dtype: float64

In [42]:
print(clean_df.shape)
clean_df.dtypes

(572287, 34)

:id                                   object
:version                              object
:created_at                           object
:updated_at                           object
borough                                int64
neighborhood                          object
building_class_category               object
tax_class_as_of_final_roll            object
block                                  int64
lot                                    int64
ease_ment                            float64
building_class_as_of_final            object
address                               object
apartment_number                      object
zip_code                             float64
residential_units                    float64
commercial_units                     float64
total_units                          float64
land_square_feet                     float64
gross_square_feet                    float64
year_built                           float64
tax_class_at_time_of_sale              int64
building_class_at_time_of             object
sale_price                             int64
sale_date                     datetime64[ns]
latitude                             float64
longitude                            float64
community_board                      float64
council_district                     float64
bin                                  float64
bbl                                  float64
census_tract_2020                    float64
nta                                   object
borough_name                          object
dtype: object

In [43]:
sql_df = clean_df[[
    'borough',
    'borough_name',
    'neighborhood',
    'building_class_category',
    'residential_units',
    'commercial_units',
    'total_units',
    'land_square_feet',
    'gross_square_feet',
    'year_built',
    'sale_price',
    'sale_date',
    'zip_code',
    'latitude',
    'longitude',
    'nta'
]].copy()

sql_df.shape

(572287, 16)

In [44]:
mysql_df = sql_df.copy()

numeric_cols = [
    'residential_units',
    'commercial_units',
    'total_units',
    'land_square_feet',
    'gross_square_feet',
    'year_built',
    'zip_code',
    'latitude',
    'longitude'
]

print(mysql_df.shape)
mysql_df.dtypes

(572287, 16)

borough                             int64
borough_name                       object
neighborhood                       object
building_class_category            object
residential_units                 float64
commercial_units                  float64
total_units                       float64
land_square_feet                  float64
gross_square_feet                 float64
year_built                        float64
sale_price                          int64
sale_date                  datetime64[ns]
zip_code                          float64
latitude                          float64
longitude                         float64
nta                                object
dtype: object

In [45]:
(mysql_df[numeric_cols] == -1).sum()

residential_units    0
commercial_units     0
total_units          0
land_square_feet     0
gross_square_feet    0
year_built           0
zip_code             0
latitude             0
longitude            0
dtype: int64

In [46]:
mysql_df[numeric_cols] = mysql_df[numeric_cols].fillna(-1)
mysql_df.to_csv(
    'nyc_property_sales_mysql.csv',
    index=False,
)

In [47]:
print(mysql_df.shape)
mysql_df.dtypes

(572287, 16)

borough                             int64
borough_name                       object
neighborhood                       object
building_class_category            object
residential_units                 float64
commercial_units                  float64
total_units                       float64
land_square_feet                  float64
gross_square_feet                 float64
year_built                        float64
sale_price                          int64
sale_date                  datetime64[ns]
zip_code                          float64
latitude                          float64
longitude                         float64
nta                                object
dtype: object

In [48]:
import os

os.path.exists('nyc_property_sales_mysql.csv')

True